# Generated by Django 3.1.1 on 2020-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
